<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2020-09-25T20:18:36 EDT" name="Default suite" finished-at="2020-09-25T20:19:04 EDT" duration-ms="28431">
    <groups>
    </groups>
    <test started-at="2020-09-25T20:18:36 EDT" name="Default test" finished-at="2020-09-25T20:19:04 EDT" duration-ms="28431">
      <class name="testcases.SignInPageTest">
        <test-method is-config="true" signature="Setup()[pri:0, instance:testcases.SignInPageTest@64cd705f]" started-at="2020-09-25T20:18:36 EDT" name="Setup" finished-at="2020-09-25T20:18:50 EDT" duration-ms="14422" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Setup -->
        <test-method signature="validateWalmartLogoDisplayed()[pri:1, instance:testcases.SignInPageTest@64cd705f]" started-at="2020-09-25T20:18:50 EDT" name="validateWalmartLogoDisplayed" finished-at="2020-09-25T20:18:51 EDT" duration-ms="425" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateWalmartLogoDisplayed -->
        <test-method is-config="true" signature="TearDown()[pri:0, instance:testcases.SignInPageTest@64cd705f]" started-at="2020-09-25T20:18:51 EDT" name="TearDown" finished-at="2020-09-25T20:18:52 EDT" duration-ms="902" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TearDown -->
        <test-method is-config="true" signature="Setup()[pri:0, instance:testcases.SignInPageTest@64cd705f]" started-at="2020-09-25T20:18:52 EDT" name="Setup" finished-at="2020-09-25T20:19:03 EDT" duration-ms="11680" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Setup -->
        <test-method signature="validateWalmartUrlAsExpected()[pri:2, instance:testcases.SignInPageTest@64cd705f]" started-at="2020-09-25T20:19:03 EDT" name="validateWalmartUrlAsExpected" finished-at="2020-09-25T20:19:03 EDT" duration-ms="16" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [https://www.walmart.ca/en] but found [https://www.walmart.ca/sign-in?from=%2Fen]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [https://www.walmart.ca/en] but found [https://www.walmart.ca/sign-in?from=%2Fen]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at testcases.SignInPageTest.validateWalmartUrlAsExpected(SignInPageTest.java:49)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateWalmartUrlAsExpected -->
        <test-method is-config="true" signature="TearDown()[pri:0, instance:testcases.SignInPageTest@64cd705f]" started-at="2020-09-25T20:19:03 EDT" name="TearDown" finished-at="2020-09-25T20:19:04 EDT" duration-ms="931" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TearDown -->
      </class> <!-- testcases.SignInPageTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
